# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - os: linux
      dist: xenial
      r: 3.2
    - os: linux
      dist: xenial
      r: oldrel
    - os: linux
      dist: xenial
      r: release
    - os: linux
      dist: xenial
      r: devel
    - os: osx
      r: release

language: R
cache: packages

# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
