# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

matrix:
  include:
    - os: linux
      dist: xenial
      r: 3.1
    - os: linux
      dist: xenial
      r: 3.2
    - os: linux
      dist: xenial
      r: oldrel
    - os: linux
      dist: xenial
      r: release
    - os: linux
      dist: xenial
      r: devel
    - os: osx
      r: release

language: R
cache: packages

before_install:
  before_install:
    - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh

after_failure:
  - ./run.sh dump_logs


# Only report coverage for the release version
after_success:
- test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
